### ISSUE TITLE
DPL-059 Biosero - Create Prod Database and check grants [Heron]

### ISSUE THREAD

**Issue by pjvv** [sanger/cherrytrack#14]
**Describe the Housekeeping**
Security - BioSero -> Cherrytrack DB (check biosero DB permissions on stored proc or specific tables in DB - psd_admin has GRANT)

**Blocking issues**
Describe any other issues or tickets that may be blocking this change.

**Additional context**

**Comment by andrewsparkes** [comment]
Database in Prod created via cherrytrack docker contain in prod using flask db upgrade as described in ReadMe.
