### ISSUE TITLE
DPL-081-2 Update Cherrytrack control 

### ISSUE THREAD

**Issue by harrietc52** [sanger/cherrytrack#20]
As R&D we would like to change the location of Heron cherrypicking controls on the Biosero system to enable the transition to strip tubes and automated control preparation.

From Biosero Technical meeting on 30th July - Update Cherrytrack config once SATs have finished. We will need to coordinate the change in config with Biosero (Rob/ Scott?)

Acceptance Criteria:

  *   Cherrytrack ‘configurations’ table should increment to a new version and implement the following changes from v1.0
     *   Control_coordinate_positive = D1
     *   Control_coordinate_negative = A1
     *   Control_excluded_destination_wells = A3, B3, D3, H3, H10, E11

Coupled with https://github.com/sanger/sequencescape/issues/3272

Contacts
Scott T

**Comment by andrewsparkes** [comment]
Done in UAT via SQL updates.
SQL queries to perform updates:

```
SELECT * FROM psd_cherrytrack_uat.configurations;

UPDATE psd_cherrytrack_uat.configurations conf
SET conf.config_value = "2.0"
WHERE conf.automation_system_id IN (1,2)
AND conf.config_key = "config_version"
;

UPDATE psd_cherrytrack_uat.configurations conf
SET conf.config_value = "Update for initial use of control strip tubes"
WHERE conf.automation_system_id IN (1,2)
AND conf.config_key = "change_description"
;

UPDATE psd_cherrytrack_uat.configurations conf
SET conf.config_value = "as28"
WHERE conf.automation_system_id IN (1,2)
AND conf.config_key = "change_user_id"
;

UPDATE psd_cherrytrack_uat.configurations conf
SET conf.config_value = "D1"
WHERE conf.automation_system_id IN (1,2)
AND conf.config_key = "control_coordinate_positive"
;

UPDATE psd_cherrytrack_uat.configurations conf
SET conf.config_value = "A1"
WHERE conf.automation_system_id IN (1,2)
AND conf.config_key = "control_coordinate_negative"
;

UPDATE psd_cherrytrack_uat.configurations conf
SET conf.config_value = "A3, B3, D3, E11, H3, H10"
WHERE conf.automation_system_id IN (1,2)
AND conf.config_key = "control_excluded_destination_wells"
;
```

**Comment by andrewsparkes** [comment]
being tested in UAT. Awaiting decision from R&D if strip tubes ready for use in Prod. Unlikely for initial go Live.

**Comment by andrewsparkes** [comment]
For Prod initial version have set excluded wells list as above in UAT:

UPDATE psd_cherrytrack_prod.configurations conf
SET conf.config_value = "A3, B3, D3, E11, H3, H10"
WHERE conf.automation_system_id IN (1,2)
AND conf.config_key = "control_excluded_destination_wells"
;

**Comment by andrewsparkes** [comment]
Added 4 additional wells to be excluded to UAT and Prod

UPDATE psd_cherrytrack_prod.configurations conf
SET conf.config_value = "A3, B3, B7, B10, C7, D3, E11, G7, H3, H10"
WHERE conf.automation_system_id IN (1,2)
AND conf.config_key = "control_excluded_destination_wells"
;
