### ISSUE TITLE
DPL-1089 [Cherrytrack] Enable dependency updates

### ISSUE THREAD

**Issue by yoldas** [sanger/cherrytrack#208]
**Describe the Housekeeping**
As a developer (ay6) I would like cherry track dependency updates enabled as GitHub workflows do not work upon merging a PR to develop branch.

**Acceptance Criteria**
- [ ] GitHub workflows authorisation issue is resolved
- [ ] Dependency updates are applied (dependabot PRs)

**Blocking issues**
No blocking issues.

**Additional context**
I think the CI fails because of configuration issue in authorisation of dependabot or the user triggering the workflows.

**Comment by TWJW-SANGER** [comment]
Archiving as project Heron is now finished.
