### ISSUE TITLE
DPL-127 Biosero - Add GBG (Green Button Go) API system status calls (C=M, V=?)

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/cherrytrack#25]
**User story**
As PSD and R&D We need a system to regularly poll the API endpoint for each system and write the status in the Cherrytrack database so that we can remotely look at the status of the Biosero systems.

**Who are the primary contacts for this story**
Scott T
Andrew
Eduardo

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] scheduled API call to fetch status for each system (every 1 minute?)
- [ ] new table 'automation_system_status' in cherrytrack database to store system status (no history?) (automation_system_id, status, updated_at)
- [ ] table accessible to Tableau

**Dependencies**
This story is blocked by the following dependencies:
- Biosero implementation of GBG API, currently WIP by Rob H on 10th Aug

References
This story has a non-blocking relationship with:
NA

**Additional context**
This story does not describe or include any dashboard or use case for displaying the statuses. Needs discussion with Scott.

**Comment by stevieing** [comment]
Ask Scott Thurston how much value this has. Could we also have the api documentation for GBG.
