### ISSUE TITLE
DPL-121 Integration test Biosero (C=M, V=3)

### ISSUE THREAD

**Issue by harrietc52** [sanger/cherrytrack#32]
**User story**
As developers we would like to have an intergration E2E testing supporting the Biosero process, simulating SAT 9

Involving:
Lighthouse UI > Lighthouse > Baracoda > Crawler > CherrytrackDB > Mongo > MLWH > Limber > SS 

**Who are the primary contacts for this story**
Harriet
Andrew
Stuart
Eduardo

**Acceptance criteria**
To be considered successful the solution must allow:

- [x] Create new test suite in Integration suite project (dont edit existing Heron LTHR)
- [x] Creates the testing run data (via LighthouseUI UAT Actions)
- [ ] Replicate the basic robot run
check correct events are fired
- [ ] To create correct data in Cherrytrack DB
check run exist
- [ ] To create correct data in Lighthouse MongoDB
- [ ] To create correct data in MLWH
- [ ] to be able to create a workflow in Limber or SS

**Additional context**
[Biosero architecture](https://lucid.app/lucidchart/cca036cc-8f97-43b8-baa8-669d68b2cb62/edit?shared=true&page=0_0#)

Existing python [script](https://github.com/sanger/biosero-sql/blob/main/python_scripts/integration_test_with_api.py) to simulate a Biosero run

**Comment by sdjmchattie** [comment]
I've done some work towards this, but the deeper I get into this with the integration-suite I realise that there are lots of complicating factors like emulating the behaviour of the Biosero robots from Ruby in the integration suite or accessing databases from that project.  The project focusses on UI interactions.  So I created an integration test of the test data creation step and made sure that the information for that run appears in the Imports page on Lighthouse UI.  I plan to put this back for someone else to consider how it could be made compatible with the SAT 9 tests.
