### ISSUE TITLE
DPL-180 [BUG] Upgrade Ubuntu server versions on FCE from v18.04 to 20.nn [C=L, V=3]

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/cherrytrack#36]
**Describe the bug**
R&D have seen a number of 'lost connection to MySQL' errors during the testing of the Biosero systems in UAT. The DBA team (David H) have told us there is a known issue with v18.04 of Ubuntu whereby it drops a connection during a refresh of the DHCP lease. Eduardo attempted applying a fix to v18.04, but we have seen a further instance of the error (31st Aug 11.34am). The solution according to the DBAs is to update the Ubuntu version from v18.04 to v20.nn
A retry on the step in the GBG software allows the user to recover and continue.

**RT Ticket Number**
730139

**To Reproduce**
Not easy to reproduce, seems to occur very rarely. DHCP lease is only updated once in 3 days according to DBAs. And has to coincide with MySQL query in progress.

**Expected behaviour**
DHCP lease renewal should not affect queries.

**Screenshots**
![Screenshot 2021-09-01 at 10 08 45](https://user-images.githubusercontent.com/3169253/131644717-efa7d9dd-cec7-4776-998e-192fdee4a925.png)

**Additional context**
Risk when upgrading OS that applications will not come back up. Have plan to revert back to v18.04 and test on UAT and Training before Prod.

**Comment by SujitDey2022** [comment]
May need to split this into individual user stories. And additional Research stories to plan the work and user stories required.

End of Life for v18.04 is 30th April 2023
